### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by itwangyu** [yuchuangu85/Launcher3-master#13]
大神你好，这个项目应该怎么编译，直接用studio报错

> Value 'main Proto source' specified for property '$1' cannot be converted to a file.
> Value 'directory 'C:\Users\Administrator\Desktop\Launcher3-o-mr1\build/extracted-protos/main'' specified for property '$2' cannot be converted to a file.
> Directory 'C:\Users\Administrator\Desktop\Launcher3-o-mr1\build\extracted-include-protos\main' specified for property '$3' does not exist.
> Value 'aospDebug Proto source' specified for property '$4' cannot be converted to a file.
> Value 'directory 'C:\Users\Administrator\Desktop\Launcher3-o-mr1\build/extracted-protos/aospDebug'' specified for property '$5' cannot be converted to a file.

**Comment by yuchuangu85** [comment]
> 大神你好，这个项目应该怎么编译，直接用studio报错
> 
> > Value 'main Proto source' specified for property '$1' cannot be converted to a file.
> > Value 'directory 'C:\Users\Administrator\Desktop\Launcher3-o-mr1\build/extracted-protos/main'' specified for property '$2' cannot be converted to a file.
> > Directory 'C:\Users\Administrator\Desktop\Launcher3-o-mr1\build\extracted-include-protos\main' specified for property '$3' does not exist.
> > Value 'aospDebug Proto source' specified for property '$4' cannot be converted to a file.
> > Value 'directory 'C:\Users\Administrator\Desktop\Launcher3-o-mr1\build/extracted-protos/aospDebug'' specified for property '$5' cannot be converted to a file.

使用默认配置的gradle版本编译，最好是：
'com.android.tools.build:gradle:3.2.1'
和
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
这样基本没问题
