### ISSUE TITLE
icon重复

### ISSUE THREAD

**Issue by xingstarx** [yuchuangu85/Launcher3-master#2]
复现步骤如下：
1. 从应用市场安装某个app，安装完成后，会触发OP_ADD事件
2. 快速点击home键，切换到launcher页面，又会触发OP_UPDATE事件

导致改app的icon出现了两个

**Comment by yuchuangu85** [comment]
@xingstarx 已经修复该问题

**Comment by xingstarx** [comment]
@yuchuangu85 cool! 真棒👍
